name: Django CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Verify Python Version
      run: |
        python --version
        echo "Python version successfully installed"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Create requirements.txt if it doesn't exist
        if [ ! -f requirements.txt ]; then
          echo "Django>=5.2.1" > requirements.txt
        fi
        pip install -r requirements.txt
        pip install flake8 pytest-django coverage

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Tests
      run: |
        python manage.py test

    - name: Generate Coverage Report
      run: |
        coverage run --source='.' manage.py test
        coverage report